### ISSUE TITLE
error on android 4.2.2 API 17

### ISSUE THREAD

**Issue by CodeoLTD** [rt2zz/react-native-contacts#38]
when I try to use the Contacts.getAll method
I receive the following error:

```
Could not invoke Contacts.getAll
invoke
BaseJavaModule.java: 262
call
NativeModuleRegistry.java 158
```

has anyone faced this issue or smothering similar?

**Comment by rt2zz** [comment]
I have not personally ran on 4.4.2. 

What version of react-native are you on?

**Comment by korkinet** [comment]
I am on react-native 0.17.0

**Comment by morenoh149** [comment]
@korkinet upgrade your RN to latest first off. Then make sure to use the latest installation instructions (they've changed).

**Comment by bansalritesh18** [comment]
@morenoh149 I am using the react native 0.20.0 and  running it on 4.1.1 API level 16. 
It is giving same error.

**Comment by morenoh149** [comment]
https://developer.android.com/reference/android/provider/ContactsContract.CommonDataKinds.Contactables.html I think the `contactables` table used was introduced in API level 18. I see RN minimum android api level is 16.

@rt2zz should we require api level >= 18 or work on using something other than contactables table to get the users? perhaps https://developer.android.com/reference/android/provider/ContactsContract.CommonDataKinds.Phone.html introduced in API level 5. But may be slower to query. A plus would be we may be able to fix the displayName concatenation mentioned in https://github.com/rt2zz/react-native-contacts/issues/39

**Comment by rt2zz** [comment]
@morenoh149 I think requiring 18+ is the way to go. Is there anyway to throw a helpful error in debug mode if run <18?

**Comment by morenoh149** [comment]
there may be a way to check the api version at runtime but I think the manifest way is the way to go (assuming it works). Not sure if it will work as this is a module that's supposed to be included in a larger project. @bansalritesh18 let us know if it throws on your app/device

**Comment by bansalritesh18** [comment]
@morenoh149  In my app, I am  targeting minimum android version 4.1 so I have to read contacts for that too. So, I have written my own module to read contacts.

**Comment by korkinet** [comment]
@bansalritesh18 
is there a chance you could share this module with us? I also need to read contacts in android 4.1
any help would be very appreciated.

**Comment by rt2zz** [comment]
@bansalritesh18 @korkinet to clarify my earlier statement, if we can get a working implementation that supports android 4.1+ and does not add undo complexity, we would gladly take a PR. 

Can you share a gist of your current implementation so we can start some discussion?

**Comment by bansalritesh18** [comment]
@rt2zz @korkinet Here is my function. It is totally in development phase. So any suggestion for improvement will be appreciated. I have checked it on 4.1 but not on higher versions , that is still pending.

 ```
@ReactMethod
public void getContacts(Callback callback) {
        ContentResolver cr = context.getContentResolver();
        Cursor cur = cr.query(ContactsContract.Contacts.CONTENT_URI,
                null, null, null, null);
        String result = "";
        WritableArray contacts = Arguments.createArray();
        if (cur.getCount() > 0) {
            while (cur.moveToNext()) {
                WritableMap contact = Arguments.createMap();
                String id = cur.getString(
                        cur.getColumnIndex(ContactsContract.Contacts._ID));
                String name = cur.getString(
                        cur.getColumnIndex(ContactsContract.Contacts.DISPLAY_NAME));
                contact.putString("recordID", id);
                contact.putString("name", name);
                if (Integer.parseInt(cur.getString(cur.getColumnIndex(ContactsContract.Contacts.HAS_PHONE_NUMBER))) > 0) {
                    Cursor pCur = cr.query(
                            ContactsContract.CommonDataKinds.Phone.CONTENT_URI,
                            null,
                            ContactsContract.CommonDataKinds.Phone.CONTACT_ID + " = ?",
                            new String[]{id}, null);
                    WritableArray phoneNumbers = Arguments.createArray();
                    while (pCur.moveToNext()) {
                        String mob = pCur.getString(pCur.getColumnIndex(ContactsContract.CommonDataKinds.Phone.NUMBER));
                        phoneNumbers.pushString(mob);
                    }
                    contact.putArray("phoneNumbers", phoneNumbers);
                    pCur.close();
                }
                contacts.pushMap(contact);
            }
            callback.invoke(contacts);
        }
    }
```

**Comment by morenoh149** [comment]
@bansalritesh18 if you could rearrange that to not use `DISPLAY_NAME` I'd love to merge it in. (I'd love to merge this in as is :+1: ).

**Comment by npomfret** [comment]
+1 It would be great to have this working in Android 4.1

**Comment by bansalritesh18** [comment]
@morenoh149 @rt2zz  Here is working implementation of reading contacts in android. I have added support of fetching the family_name and given_name. This is in development phase. Any suggestion for improvement would be appreciated.
https://github.com/bansalritesh18/react-native-contacts.git

**Comment by npomfret** [comment]
Hey - are there any plans to make this work on android 4.1?  I'm getting this error:

```
java.lang.RuntimeException: Could not invoke Contacts.getAll
...
Caused by: java.lang.reflect.InvocationTargetException
...
Caused by: java.lang.NoClassDefFoundError: android.provider.ContactsContract$CommonDataKinds$Contactables


```

**Comment by morenoh149** [comment]
I merged it in. @npomfret please confirm it works as before. And cosider returning `family_name` and `given_name` now instead of `display_name` so the ios and android versions are the same :)

**Comment by npomfret** [comment]
Thanks for the merge.  I've tested it on 4.1.2, and will test on 5x later.  Will let you know if there are any problems.
